### ISSUE TITLE
Fetch map from server and display on client

### ISSUE THREAD

**Issue by MikeKlemarewski** [sfu-innovation/WifiLocator#21]
I want to be able to view my location on a map.  The server should send the client a maps showing their location.

**Comment by MikeKlemarewski** [comment]
Jordan is going to set up a way of serving the pictures.  Talk to him about what kind of request should be made.  The picture should display on the main activity below the zone information

**Comment by alex-kwan** [comment]
Moving to milestone 3 in order to be in parallel with server development schedule for map data

**Comment by alex-kwan** [comment]
I think we're all done this one now. CLOSING :D
