### ISSUE TITLE
update server getmap feature to serve new map images to clients

### ISSUE THREAD

**Issue by jrf2** [sfu-innovation/WifiLocator#25]
now that map images have been created for each zone we need to have the get map method return the correct file name of the image associated with a zone. The get map function already exists so I believe this should involve just be a simple updating of the database tables. Also we need to find and document the image url for the client users.

**Comment by jrf2** [comment]
the server wasnt serving images because some of the folders had change. I have fixed it so now all images will be found at:
http://wifi-location.appspot.com/media/
and the zone maps will be in a sub directory called zonemaps:
http://wifi-location.appspot.com/media/zonemaps/map1.png

I still need to fix the getmaps function to associate an image file with a zone

committed in change:
https://github.com/sfu-innovation/WifiLocator/commit/2cdf3bbdf556a25e33bf53ae409262b38b2aaf89

**Comment by jrf2** [comment]
/getmap/<zone_id> function on the server is now working properly, although I don't remember if zone_id was the argument that we agreed on for accessing the area name and image file name. I will find out if this is what we want and then close this issue once I have done that.

**Comment by hrl1** [comment]
zone_id is currently not being returned with /getfriends/ requests so if you guys could either name the map files based on location (eg. "AQZone1.png"), or add zone_id  to the response for getfriends, that would be great. Thanks.

**Comment by jrf2** [comment]
getzone request now returns a map_name field which has the path to the image file. (ex. map_name = "/media/zonemaps/map1.png") this allows you to get the image name using the BSSID instead of using the zone_id.

**Comment by hrl1** [comment]
can you also add one for /getfriends/ to return maps for friend locations?
