### ISSUE TITLE
Json response for pending friend requests returns requests #'s as strings

### ISSUE THREAD

**Issue by MikeKlemarewski** [sfu-innovation/WifiLocator#37]
Request: http://wifi-location.appspot.com/request/pending/friendships

Body: {"user_id" : 28001} 

Response: {"status": 0, "requests": [{"friend_name": "Jordan", "request_id": "45011"}]}

I think the request_id should be an int instead of a string to keep consistency.  To accept the friend request we have to pass the request_id as an int.  Let me know if you think otherwise.

**Comment by catherinettt** [comment]
Agree, I will fix that.

**Comment by catherinettt** [comment]
fixed
