### ISSUE TITLE
getfriends should return for invalid get requests

### ISSUE THREAD

**Issue by catherinettt** [sfu-innovation/WifiLocator#4]
http://wifi-location.appspot.com/getfriends/Betty

should return:
{"Betty":  Unknown}

**Comment by jrf2** [comment]
this issue should not be resolved in master and deployed to the server. Here is a link to the details of this commit:
https://github.com/sfu-innovation/WifiLocator/commit/388ffc7f91b20edafbcb16c9828701fd859b7a00
