### ISSUE TITLE
getzone should return for invalid get requests

### ISSUE THREAD

**Issue by catherinettt** [sfu-innovation/WifiLocator#5]
http://wifi-location.appspot.com/getzone/Betty/00:1f:45:64:16:c8

Should return: 
{"zone_id": -1, "user_location": -1, "last_update": "Unknown", "user": "Unknown", "mac_address": "00:1f:45:64:16:c8", "zone_name": "Unknown"}

http://wifi-location.appspot.com/getzone/Catherine/00:1f:45:64:16:xx
Should return: 
{"zone_id": -1, "user_location": -1, "last_update": "Unknown", "user": "Catherine", "mac_address": "Unknown", "zone_name": "Unknown"}

**Comment by jrf2** [comment]
This issue should now be resolved in master and deployed on the server
