### ISSUE TITLE
add pictures to rows of tweets

### ISSUE THREAD

**Issue by alex-kwan** [sfu-innovation/WifiLocator#7]
implement a fast way to lazy load images for each user in twitter

**Comment by MikeKlemarewski** [comment]
Might do this for android as well.  As of now it's just grabbing text.

**Comment by alex-kwan** [comment]
getting images can be an expensive operation. Try to load in background thread if you are going to do this

**Comment by alex-kwan** [comment]
Closing since IOS app can't handle handover BSSID strings
